const FETCH_MOVIE_LOADING = 'FETCH_MOVIE_LOADING';
const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
const FETCH_MOVIE_FAIL = 'FETCH_MOVIE_FAIL';
const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
const SET_CURRENT_MOVIE = 'SET_CURRENT_MOVIE';

export {
  FETCH_MOVIE_LOADING,
  FETCH_MOVIE_SUCCESS,
  FETCH_MOVIE_FAIL,
  ADD_TO_WATCHLIST,
  REMOVE_FROM_WATCHLIST,
  SET_CURRENT_MOVIE
};
