//search details
const UPDATE_QUERY_DETAILS = 'UPDATE_QUERY_DETAILS';

//MOVIE LIST
const FETCH_MOVIE_LIST_LOADING = 'FETCH_MOVIE_LIST_LOADING';
const FETCH_MOVIE_LIST_SUCCESS = 'FETCH_MOVIE_LIST_SUCCESS';
const FETCH_MOVIE_LIST_FAIL = 'FETCH_MOVIE_LIST_FAIL';

//buffer action
const LOAD_BUFFER = 'LOAD_BUFFER';

//WATCH LIST
const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';

//MOVIE DETAILS
const FETCH_MOVIE_DETAIL_LOADING = 'FETCH_MOVIE_DETAIL_LOADING';
const FETCH_MOVIE_DETAIL_SUCCESS = 'FETCH_MOVIE_DETAIL_SUCCESS';
const FETCH_MOVIE_DETAIL_FAIL = 'FETCH_MOVIE_DETAIL_FAIL';

export {
  FETCH_MOVIE_LIST_LOADING,
  FETCH_MOVIE_LIST_SUCCESS,
  FETCH_MOVIE_LIST_FAIL,
  ADD_TO_WATCHLIST,
  REMOVE_FROM_WATCHLIST,
  FETCH_MOVIE_DETAIL_LOADING,
  FETCH_MOVIE_DETAIL_SUCCESS,
  FETCH_MOVIE_DETAIL_FAIL,
  UPDATE_QUERY_DETAILS,
  LOAD_BUFFER
};
